export const teacherEx = [
  {
    id: 'Math',
    name:"Pablo Escobar",
    description:
      'A math teacher is a professional educator who specializes in teaching mathematics to students. They are responsible for developing and delivering lesson plans, assignments, and assessments that cover a range of mathematical concepts and skills. They work with students of various ages and levels of mathematical proficiency, from elementary school to university-level courses.Math teachers must be knowledgeable in a wide range of mathematical topics, including arithmetic, algebra, geometry, trigonometry, calculus, and statistics. They must also be skilled in explaining mathematical concepts in a way that is accessible and engaging to students, and in helping students develop problem-solving strategies.In addition to teaching, math teachers may also be responsible for grading assignments and exams, providing feedback to students and parents, participating in parent-teacher conferences, and maintaining classroom discipline and order.Overall, a math teacher plays a critical role in helping students develop the mathematical skills and knowledge they need to succeed in a variety of academic and professional settings.',
  },
  {
    id: 'Science',
    name:"Ioana Tudor",
    description:
      'A science teacher is a professional educator who specializes in teaching science to students. They are responsible for developing and delivering lesson plans, assignments, and assessments that cover a range of scientific concepts and skills. They work with students of various ages and levels of scientific proficiency, from elementary school to university-level courses.Science teachers must be knowledgeable in a wide range of scientific topics, including biology, chemistry, physics, environmental science, earth science, and more. They must also be skilled in explaining scientific concepts in a way that is accessible and engaging to students, and in helping students develop critical thinking and problem-solving skills.In addition to teaching, science teachers may also be responsible for grading assignments and exams, providing feedback to students and parents, participating in parent-teacher conferences, and maintaining classroom discipline and order.Science teachers may also be involved in organizing and supervising science fairs, field trips, and other extracurricular activities related to science. They may also collaborate with other teachers and professionals to develop interdisciplinary projects that integrate science with other subject areas.Overall, a science teacher plays a critical role in helping students develop the scientific literacy and skills they need to succeed in a variety of academic and professional settings, as well as in fostering a curiosity and passion for science that can inspire lifelong learning.',
  },
  {
    id: 'Sport',
    name:"Adrian Cristea",
    description:
      'A sport teacher is a professional educator who specializes in teaching physical education and sports to students. They are responsible for developing and delivering lesson plans, activities, and assessments that promote physical fitness, teamwork, and sportsmanship. They work with students of all ages, from elementary school to university-level courses.Sport teachers must be knowledgeable in a wide range of physical activities and sports, including but not limited to soccer, basketball, volleyball, gymnastics, track and field, swimming, and more. They must also be skilled in explaining and demonstrating proper techniques and safety practices, as well as in helping students develop coordination, endurance, and strength.In addition to teaching, sport teachers may also be responsible for grading assignments and assessments, providing feedback to students and parents, participating in parent-teacher conferences, and maintaining a safe and inclusive classroom environment.Sport teachers may also be involved in organizing and supervising intramural sports leagues, tournaments, and other extracurricular activities related to physical fitness and sports. They may also collaborate with other teachers and professionals to promote physical activity and wellness throughout the school community.Overall, a sport teacher plays a critical role in promoting physical fitness and wellness, as well as in helping students develop important life skills such as teamwork, leadership, and sportsmanship.',
  },
  {
    id: 'History',
    name:"Florin Dumitru",
    description:
      'A history teacher is a professional educator who specializes in teaching history to students. They are responsible for developing and delivering lesson plans, assignments, and assessments that cover a range of historical events, people, and cultures. They work with students of various ages and levels of historical proficiency, from elementary school to university-level courses.History teachers must be knowledgeable in a wide range of historical topics, including but not limited to world history, American history, European history, ancient history, and more. They must also be skilled in explaining historical concepts in a way that is accessible and engaging to students, and in helping students develop critical thinking and analytical skills.In addition to teaching, history teachers may also be responsible for grading assignments and exams, providing feedback to students and parents, participating in parent-teacher conferences, and maintaining classroom discipline and order.History teachers may also be involved in organizing and supervising historical simulations, debates, and other extracurricular activities related to history. They may also collaborate with other teachers and professionals to develop interdisciplinary projects that integrate history with other subject areas.Overall, a history teacher plays a critical role in helping students develop an understanding of the past and how it informs the present, as well as in fostering a curiosity and passion for history that can inspire lifelong learning.',
  },
  {
    id: 'Economics',
    name:"Capy Capibara",
    description:
      'An economics teacher is a professional educator who specializes in teaching economics to students. They are responsible for developing and delivering lesson plans, assignments, and assessments that cover a range of economic concepts, principles, and theories. They work with students of various ages and levels of economic proficiency, from high school to university-level courses.Economics teachers must be knowledgeable in a wide range of economic topics, including but not limited to microeconomics, macroeconomics, international economics, economic systems, and more. They must also be skilled in explaining economic concepts in a way that is accessible and engaging to students, and in helping students develop critical thinking and analytical skills.In addition to teaching, economics teachers may also be responsible for grading assignments and exams, providing feedback to students and parents, participating in parent-teacher conferences, and maintaining classroom discipline and order.Economics teachers may also be involved in organizing and supervising economic simulations, debates, and other extracurricular activities related to economics. They may also collaborate with other teachers and professionals to develop interdisciplinary projects that integrate economics with other subject areas.Overall, an economics teacher plays a critical role in helping students develop an understanding of how the economy works, as well as in fostering a curiosity and passion for economics that can inspire lifelong learning. They can prepare students for careers in economics, finance, and business, as well as equip them with skills and knowledge that are valuable in a variety of other fields.',
  },
];
